# bacon.toml
default_job = "all"

[jobs.all]
command = ["cargo", "check"]
need_stdout = false
watch = ["src/", "tests/"]
on_success = ["clippy", "test", "fmt"]

[jobs.clippy]
command = ["cargo", "clippy", "--", "-D", "warnings"]
need_stdout = false
watch = ["src/", "tests/"]

[jobs.test]
command = ["cargo", "test"]
need_stdout = true
watch = ["src/", "tests/"]

[jobs.fmt]
command = ["cargo", "fmt", "--check"]
need_stdout = false
watch = ["src/", "tests/"]