# bacon.toml
# Default job runs all checks
default_job = "check-all"

[jobs.check-all]
command = ["cargo", "check"]
need_stdout = false
watch = ["src/", "tests/"]
on_success = "job:clippy-all"

[jobs.clippy-all]
command = ["cargo", "clippy", "--", "-D", "warnings"]
need_stdout = false
watch = ["src/", "tests/"]
on_success = "job:test-all"

[jobs.test-all]
command = ["cargo", "test"]
need_stdout = true
watch = ["src/", "tests/"]
on_success = "job:fmt-all"

[jobs.fmt-all]
command = ["cargo", "fmt"]
need_stdout = false
watch = ["src/", "tests/"]

# Individual jobs for running specific checks
[jobs.check]
command = ["cargo", "check"]
need_stdout = false
watch = ["src/", "tests/"]

[jobs.clippy]
command = ["cargo", "clippy", "--", "-D", "warnings"]
need_stdout = false
watch = ["src/", "tests/"]

[jobs.test]
command = ["cargo", "test"]
need_stdout = true
watch = ["src/", "tests/"]

[jobs.coverage]
command = ["cargo", "tarpaulin", "--out", "Html"]
need_stdout = true

[jobs.mutants]
command = ["sh", "-c", "rm -rf mutants.out html/mutants.out 2>/dev/null; cargo mutants --output html > mutation-report.html"]
need_stdout = true

[jobs.fmt]
command = ["cargo", "fmt"]
need_stdout = false
watch = ["src/", "tests/"]

# Install job
[jobs.install]
command = ["cargo", "build", "--release"]
need_stdout = true
watch = ["src/", "tests/"]
on_success = "job:install-binary"

[jobs.install-binary]
command = ["cargo", "install", "--path", "."]
need_stdout = true