[package]
name = "zrt"
version = "0.1.0"
edition = "2021"

[dependencies]
walkdir = "2.5.0"
anyhow = "1.0.95"
clap = { version = "4.5.26", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
tempfile = "3.8"
glob = "0.3.2"

[lints.clippy]
unwrap_used = "deny"
