[package]
name = "zrt"
version = "0.1.0"
description = "A zettelkasten refactoring tool"
authors = ["Craig Hill craigthomashill@gmail.com>"]
license = "MIT"
edition = "2024"
repository = "https://github.com/craigtkhill/zettelkasten-refactor-tool"
keywords = ["zettelkasten", "notes", "refactoring"]
categories = ["command-line-utilities"]

[dependencies]
walkdir = "2.5.0"
anyhow = "1.0.95"
clap = { version = "4.5.26", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
tempfile = "3.8"
glob = "0.3.2"
toml = "0.8.19"
