[package]
name = "zrt"
version = "0.1.0"
description = "A zettelkasten refactoring tool"
authors = ["Craig Hill craigthomashill@gmail.com>"]
license = "MIT"
edition = "2024"
repository = "https://github.com/craigtkhill/zettelkasten-refactor-tool"
keywords = ["zettelkasten", "notes", "refactoring"]
categories = ["command-line-utilities"]

[dependencies]
walkdir = "2.5.0"
anyhow = "1.0.96"
clap = { version = "4.5.30", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml_ng = "0.10"
tempfile = "3.17"
glob = "0.3.2"
toml = "0.8.20"

[lints.clippy]
cargo        = { priority = -1, level = "deny" }
complexity   = { priority = -1, level = "deny" }
correctness  = { priority = -1, level = "deny" }
perf         = { priority = -1, level = "deny" }
suspicious   = { priority = -1, level = "deny" }
style        = { priority = -1, level = "deny" }
pedantic     = { priority = -1, level = "deny" }
restriction  = { priority = -1, level = "deny" }
nursery      = { priority = -1, level = "deny" }

# cargo clippy 2>&1 | grep https://rust-lang.github.io/rust-clippy/master/index.html | sed 's/^.*#//' | sort | uniq | xargs -I % echo '% = "allow"' >> Cargo.toml
missing_docs_in_private_items = "allow"
missing_inline_in_public_items = "allow"

# definitely keeping lints
blanket_clippy_restriction_lints = "allow"
exhaustive_structs = "allow"
filetype_is_file = "allow"
float_arithmetic = "allow"
implicit_return = "allow"
min_ident_chars = "allow"
print_stdout = "allow"
pub_use = "allow"
question_mark_used = "allow"
self_named_module_files = "allow"
shadow_reuse = "allow"
single_call_fn = "allow"
